substitutions:
  log_level: none
  log_baud_rate: '115200'
  flash_write_interval: 10min

esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  name_add_mac_suffix: false
  build_path: ./build/${device_id}

preferences:
  flash_write_interval: ${flash_write_interval}

packages:
  api:              !include api/api.yaml
  ota:              !include ota/ota.yaml
  logger:           !include logger/logger.yaml
  status_sensor:    !include binary_sensor/status.yaml
  uptime_sensor:    !include sensor/uptime.yaml
  restart_button:   !include button/restart.yaml
  version_sensor:   !include text_sensor/version.yaml
  time:             !include time/time.yaml
