substitutions:
  device_id: basement-bathroom-light-fan
  device_name: Basement Bathroom Light and Fan
  board: esp01_1m
  ip_address: !secret basement-bathroom-light-fan-ip
  ota_pwd: !secret basement-bathroom-light-fan-ota-pwd
  api_pwd: !secret basement-bathroom-light-fan-api-pwd
  ap_wifi_pwd: !secret basement-bathroom-light-fan-ap-pwd

packages:
  device_base: !include ./packages/device_base_esp8266.yaml

external_components:
  - source:
      type: local
      path: ./components 
    components: [ binary_light_with_power ]

binary_sensor:
  - platform: gpio
    id: light_button
    pin:
      number: 12
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: the_light
  - platform: gpio
    id: fan_button
    pin:
      number: 3
      mode: INPUT_PULLUP
    on_press:
      then:
        - fan.toggle: the_fan

fan:
  - platform: binary
    id: the_fan
    output: fan_output
    name: "Basement Bathroom Fan"

light:
  - platform: binary_light_with_power
    id: the_light
    name: "Basement Bathroom Light"
    output: light_output
    power:
      id: light_power
      name: Basement Bathroom Light Power
      light_wattage: 48.0

output:
  - platform: gpio
    id: fan_output
    pin: 4
  - platform: gpio
    id: light_output
    pin: 13

status_led:
  pin:
    number: 0
    inverted: true

sensor:
  - platform: total_daily_energy
    name: Basement Bathroom Light
    power_id: light_power
    method: left
