substitutions:
  device_id: basement-tv
  device_name: Basement TV
  ip_address: !secret basement-tv-ip
  ota_pwd: !secret basement-tv-ota-pwd
  api_key: !secret basement-tv-key
  ap_wifi_pwd: !secret basement-tv-ap-pwd

packages:
  feit_dimmer: !include ./packages/topgreener_smart_plug.yaml
