substitutions:
  device_id: basement-tv
  device_name: Basement TV
  ip_address: !secret basement_tv_ip
  api_key: !secret basement_tv_key
  pwd: !secret basement_tv_pwd

packages:
  feit_dimmer: !include ./packages/topgreener_smart_plug.yaml
