substitutions:
  device_id: basement-fridge
  device_name: Basement Fridge
  api_key: !secret basement_fridge_key
  pwd: !secret basement_fridge_pwd

packages:
  device_base: !include ./packages/topgreener_smart_plug.yaml
