# Board: NodeMCU-32S (NodeMCU)
# Definition: definitions/boards/nodemcu-32s/manifest.yaml

esphome:
  name: bt-proxy-basement
  friendly_name: Basement Bluetooth Proxy

esp32:
  variant: esp32
  flash_size: 4MB
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret bt_proxy_basement_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
