substitutions:
  device_id: garage-lights
  device_name: Garage Lights
  api_key: !secret garage_lights_key
  pwd: !secret garage_lights_pwd
  light_wattage: '378'

packages:
  device_base: !include ./packages/shelly_1l.yaml
