substitutions:
  device_id: garage-lights
  device_name: Garage Lights
  ip_address: !secret garage-lights-ip
  ota_pwd: !secret garage-lights-ota-pwd
  api_pwd: !secret garage-lights-api-pwd
  ap_wifi_pwd: !secret garage-lights-ap-pwd
  light_wattage: '378'

packages:
  shelly_1l: !include ./packages/shelly_1l.yaml
