substitutions:
  device_id: hvac
  device_name: HVAC
  api_key: !secret hvac_key
  pwd: !secret hvac_pwd
  zone1name: Main Floor
  zone2name: Upstairs
  zone3name: Basement

external_components:
  - source:
      type: local
      path: ./components 
    components: [ econet_zone_control ]

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    files: [
      econet_hvac_furnace.yaml,
      econet_hvac_odu.yaml,
      hvac-zone-yaml/econet_hvac_zone123status.yaml,
      hvac-zone-yaml/econet_hvac_zone1.yaml,
      hvac-zone-yaml/econet_hvac_zone2.yaml,
      hvac-zone-yaml/econet_hvac_zone3.yaml
    ]
  device_base: !include ./packages/econet_base.yaml

climate:
  - platform: econet_zone_control
    id: home
    name: Home
    econet_id: econet_id
    request_mod: 10
    request_once: false
    src_address: 0x380
    operating_mode_datapoint: HVACMODE
    mode_datapoint: STATMODE
    modes:
      0: heat
      1: cool
      2: heat_cool
      3: fan_only
      4: "off"
    current_temperature_datapoint: SPT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    fan_mode_datapoint: STAT_FAN
    fan_mode_no_schedule_datapoint: STATNFAN
    current_humidity_datapoint: RELH7005
    zones:
      - src_address: 0x380
        request_mod: 10
        is_primary: true
      - src_address: 0x680
        request_mod: 11
      - src_address: 0x681
        request_mod: 12
    automatic_fan_mode: 0
    fan_modes:
      - fan_mode: 1
        minimum_temperature_delta: 0°F
      - fan_mode: 2
        minimum_temperature_delta: 0.4°F
      - fan_mode: 3
        minimum_temperature_delta: .8°F
      - fan_mode: 4
        minimum_temperature_delta: 1.2°F
    visual:
      min_temperature: 60°F
      max_temperature: 80°F
      temperature_step:
        current_temperature: 0.1°F
        target_temperature: 1°F

sensor:
 - id: !extend thermostat_current_humidity
   internal: true
