substitutions:
  device_id: hvac
  device_name: HVAC
  board: esp32dev
  api_key: !secret hvac_key
  pwd: !secret hvac_pwd
  zone1name: Main Floor
  zone2name: Upstairs
  zone3name: Basement

external_components:
  - source:
      type: local
      path: ./components 
    components: [ econet_zones_climate ]

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    files: [
      econet_hvac_furnace.yaml,
      econet_hvac_odu.yaml,
      hvac-zone-yaml/econet_hvac_zone123status.yaml,
      hvac-zone-yaml/econet_hvac_zone1.yaml,
      hvac-zone-yaml/econet_hvac_zone2.yaml,
      hvac-zone-yaml/econet_hvac_zone3.yaml
    ]
  device_base: !include ./packages/device_base_esp32.yaml

button:
  - id: !extend restart_esp
    internal: true

climate:
  - platform: econet_zones_climate
    id: home
    name: Home
    operating_mode_sensor: operating_mode
    zones:
      - zone1_climate
      - zone2_climate
      - zone3_climate
    automatic_fan_mode: Automatic
    fan_modes:
      - fan_mode: Speed 1 (Low)
        minimum_temperature_delta: 0°F
      - fan_mode: Speed 2 (Medium Low)
        minimum_temperature_delta: .5°F
      - fan_mode: Speed 3 (Medium)
        minimum_temperature_delta: 1.0°F
    visual:
      min_temperature: 60°F
      max_temperature: 80°F
      min_humidity: 25
      max_humidity: 60
      temperature_step:
        current_temperature: .1°F
        target_temperature: .5°F

sensor:
  - id: !extend wifi_signal_sensor
    internal: true

# If you have UNSUPPORTED sensors add something like the following to disable them
# sensor:
#   - id: !extend hot_water
#     request_mod: none
#     internal: true
