substitutions:
  device_id: kitchen-fridge
  device_name: Kitchen Fridge
  ip_address: !secret kitchen_fridge_ip
  api_key: !secret kitchen_fridge_key
  pwd: !secret kitchen_fridge_pwd

packages:
  feit_dimmer: !include ./packages/topgreener_smart_plug.yaml
