substitutions:
  device_id: "main-garage-door"
  device_name: Main Garage Door
  board: d1_mini
  api_key: !secret main_garage_door_key
  pwd: !secret main_garage_door_pwd
  flash_write_interval: 5s

packages:
  ratgdo: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
  device_base: !include ./packages/device_base_esp8266.yaml

button:
  - id: !remove ${id_prefix}_restart
  - id: !remove ${id_prefix}_safe_mode

ota:
  - id: !remove ${id_prefix}_ratgdo_ota

text_sensor:
  - id: !remove ${id_prefix}_firmware_version

web_server: !remove
