substitutions:
  device_id: master-bed
  device_name: Master Bed
  board: nodemcuv2
  api_key: !secret master_bed_key
  pwd: !secret master_bed_pwd

packages:
  device_base: !include ./packages/device_base_esp8266.yaml

external_components:
  - source:
      type: local
      path: ./components 
    components: [ bed_sensor ]

sensor:
  - platform: adc
    id: adc_sensor
    pin: A0
    raw: True
    update_interval: never

bed_sensor:
  adc_sensor: adc_sensor
  side_one:
    name: Melissa is in Bed
    status_name: Melissa
    output: melissa_out
    value_sensor:
      name: Melissa Value
  side_two:
    name: Chris is in Bed
    status_name: Chris
    output: chris_out
    value_sensor:
      name: Chris Value
  someone_sensor:
    name: Someone is in Bed
    status_name: Someone
  count_sensor:
    name: Count
  status_sensor:
    name: Status

output:
  - platform: gpio
    id: melissa_out
    pin: D2
  - platform: gpio
    id: chris_out
    pin: D1
