substitutions:
  device_id: master-bath-fan
  device_name: Master Bathroom Fan
  ip_address: !secret master-bath-fan-ip
  ota_pwd: !secret master-bath-fan-ota-pwd
  api_pwd: !secret master-bath-fan-api-pwd
  ap_wifi_pwd: !secret master-bath-fan-ap-pwd
  fan_wattage: "26.6"

packages:
  device_base: !include ./packages/feit_dimmer_as_fan.yaml
