substitutions:
  device_id: basement_stair_lights_2
  device_name: Basement Stair Lights 2
  ip_address: !secret basement-stair-lights-2-ip
  ota_pwd: !secret basement-stair-lights-2-ota-pwd
  api_pwd: !secret basement-stair-lights-2-api-pwd
  ap_wifi_pwd: !secret basement-stair-lights-2-ap-pwd

script:
  - id: double_click
    then:
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: switch.basement_tv, switch.xbox, light.basement_tv, light.basement, light.bar, switch.pool_table_light, light.basement_bathroom_light, light.basement_shower_light

packages:
  feit_dimmer: !include ../packages/feit_dimmer_without_power.yaml

light:
  - platform: tuya_light_plus
    id: tuya_light
    name: ${device_name}
    switch_datapoint: 1
    dimmer_datapoint: 2
    max_value: 1000
    linked_lights:
      - light.basement_stair_lights
    day_night:
      sensor_id: sensor.day_night
      sensor_type: text
      sensor_day_value: Day
      sensor_night_value: Night
      day_default_brightness: 255
      night_default_brightness: 1
      day_auto_off_time: 0 min
      night_auto_off_time: 15 min
    on_double_click_while_off:
      - script.execute: double_click
    double_click_while_off_stays_off: true
    on_double_click_while_on:
      - script.execute: double_click
