substitutions:
  device_id: basement_bath_shower_light_heat
  device_name: Basement Bathroom Shower Light and Heater
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret basement_bathroom_shower_light_heater_ip
  ota_pwd: !secret basement_bathroom_shower_light_heater_ota_pwd
  api_pwd: !secret basement_bathroom_shower_light_heater_api_pwd
  ap_wifi_pwd: !secret basement_bathroom_shower_light_heater_ap_wifi_pwd

packages:
  device_base: !include ../packages/device_base.yaml

external_components:
  - source:
      type: local
      path: ../components 
    components: [ binary_light_with_power, gpio_switch_with_power ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]
  - source: github://esphome/esphome@dev
    components: [ total_daily_energy ]

binary_sensor:
  - platform: gpio
    id: light_button
    pin:
      number: 12
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: the_light
  - platform: gpio
    id: heater_button
    pin:
      number: 3
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: heater

espsense:
  plugs:
    - name: Basement Shower Light
      power_sensor: light_power
      voltage: 120
    - name: Basement Bathroom Heater
      power_sensor: heat_power
      voltage: 120

light:
  - platform: binary_light_with_power
    id: the_light
    name: Basement Shower Light
    output: light_output
    power:
      id: light_power
      name: Basement Shower Light Power
      light_wattage: 11.5

output:
  - platform: gpio
    id: light_output
    pin: 13

status_led:
  pin:
    number: 0
    inverted: true

switch:
  - platform: gpio_switch_with_power
    id: heater
    name: Basement Bathroom Heater
    icon: mdi:radiator
    pin: 4
    power:
      id: heat_power
      name: Basement Bathroom Heater Power
      device_wattage: 500.0

sensor:
  - platform: total_daily_energy
    name: Basement Shower Light
    power_id: light_power
    method: left
    min_save_interval: 10min
  - platform: total_daily_energy
    name: Basement Bathroom Heater
    power_id: heat_power
    method: left
    min_save_interval: 10min

time:
  - platform: homeassistant
