substitutions:
  device_id: basement_stair_lights
  device_name: Basement Stair Lights
  ip_address: !secret basement_stair_lights_ip
  ota_pwd: !secret basement_stair_lights_ota_pwd
  api_pwd: !secret basement_stair_lights_api_pwd
  ap_wifi_pwd: !secret basement_stair_lights_ap_wifi_pwd
  day_brightness: "1"
  night_brightness: ".03"
  day_auto_off_minutes: "0"
  night_auto_off_minutes: "15"
  linked_lights: "light.basement_stair_lights_2"
  double_tap_while_off_stays_on: "false"

script:
  - id: startup
    then:
      - lambda: |-
          TuyaLight->add_double_tap_callback([]() { double_tap->execute(); });

  - id: double_tap
    then:
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: switch.basement_tv, switch.xbox, light.basement_tv, light.basement, light.bar, switch.pool_table_light, light.basement_bathroom_light, light.basement_shower_light

packages:
  feit_dimmer: !include ../packages/feit_dimmer.yaml
