substitutions:
  device_id: basement_bathroom_light_fan
  device_name: Basement Bathroom Light and Fan
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret basement_bathroom_light_fan_ip
  ota_pwd: !secret basement_bathroom_light_fan_ota_pwd
  api_pwd: !secret basement_bathroom_light_fan_api_pwd
  ap_wifi_pwd: !secret basement_bathroom_light_fan_ap_wifi_pwd

packages:
  device_base: !include ../packages/device_base.yaml

external_components:
  - source:
      type: local
      path: ../components 
    components: [ binary_light_with_power ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]
  - source: github://esphome/esphome@dev
    components: [ total_daily_energy ]

binary_sensor:
  - platform: gpio
    id: light_button
    pin:
      number: 12
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: the_light
  - platform: gpio
    id: fan_button
    pin:
      number: 3
      mode: INPUT_PULLUP
    on_press:
      then:
        - fan.toggle: the_fan

espsense:
  plugs:
    - name: Basement Bathroom Light
      power_sensor: light_power
      voltage: 120

fan:
  - platform: binary
    id: the_fan
    output: fan_output
    name: "Basement Bathroom Fan"

light:
  - platform: binary_light_with_power
    id: the_light
    name: "Basement Bathroom Light"
    output: light_output
    power:
      id: light_power
      name: Basement Bathroom Light Power
      light_wattage: 48.0

output:
  - platform: gpio
    id: fan_output
    pin: 4
  - platform: gpio
    id: light_output
    pin: 13

status_led:
  pin:
    number: 0
    inverted: true

sensor:
  - platform: total_daily_energy
    name: Basement Bathroom Light
    power_id: light_power
    method: left
    min_save_interval: 10min

time:
  - platform: homeassistant
