substitutions:
  device_id: family-room-tv
  device_name: Family Room TV
  ip_address: !secret family-room-tv-ip
  ota_pwd: !secret family-room-tv-ota-pwd
  api_pwd: !secret family-room-tv-api-pwd
  ap_wifi_pwd: !secret family-room-tv-ap-pwd
  wifi_ssid: !secret new-wifi-ssid
  wifi_password: !secret new-wifi-password
  ip_subnet: !secret new-ip-subnet
  ip_gateway: !secret new-ip-gateway

wifi:
  use_address: 192.168.128.46

packages:
  feit_dimmer: !include ../packages/topgreener_smart_plug.yaml
