substitutions:
  device_id: front_lights
  device_name: Front Lights
  ip_address: !secret front_lights_ip
  ota_pwd: !secret front_lights_ota_pwd
  api_pwd: !secret front_lights_api_pwd
  ap_wifi_pwd: !secret front_lights_ap_wifi_pwd

packages:
  feit_dimmer: !include ../packages/feit_dimmer.yaml

light:
  - platform: tuya_light_plus
    id: tuya_light
    name: ${device_name}
    switch_datapoint: 1
    dimmer_datapoint: 2
    max_value: 1000
    default_brightness: 255
    auto_off_time: 30 min
    on_double_click_while_off:
      - lambda: tuya_tuyalightplus->set_auto_off_time(0);
    double_click_while_off_stays_off: false
    on_turn_off:
      - lambda: tuya_tuyalightplus->set_auto_off_time(30 * 60 * 1000);
