substitutions:
  device_id: second_garage_door
  device_name: Second Garage Door
  platform: ESP8266
  board: d1_mini
  ip_address: !secret second_garage_door_ip
  ota_pwd: !secret second_garage_door_ota_pwd
  api_pwd: !secret second_garage_door_api_pwd
  ap_wifi_pwd: !secret second_garage_door_ap_wifi_pwd

packages:
  device_base: !include ../packages/device_base.yaml

esphome:
  includes:
  - ../custom/GarageDoor.h

cover:
- platform: custom
  lambda: |-
    GarageDoor = new GarageDoorCover(D1, D2, D4, D5, D6);
    GarageDoor->set_rtttl_buzzer(rtttl_rtttl);
    App.register_component(GarageDoor);
    return {GarageDoor};
  covers:
    - name: ${device_name}

binary_sensor:
  - platform: custom
    lambda: |-
      auto lock = GarageDoor->get_lock_sensor();
      App.register_component(lock);
      return {lock};
    binary_sensors:
      name: ${device_name}
      device_class: lock

output:
  - platform: esp8266_pwm
    pin: D7
    id: rtttl_out

rtttl:
  output: rtttl_out