substitutions:
  device_id: garage-fridge
  device_name: Garage Fridge
  platform: ESP32
  board: wemos_d1_mini32
  ip_address: !secret garage-fridge-ip
  ota_pwd: !secret garage-fridge-ota-pwd
  api_pwd: !secret garage-fridge-api-pwd
  ap_wifi_pwd: !secret garage-fridge-ap-pwd
  Xlog_level: debug

packages:
  device_base: !include ../packages/device_base.yaml

external_components:
  - source:
      type: local
      path: ../components 
    components: [ garage_fridge ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

esp32_ble_tracker:
  scan_parameters:
    interval: 16ms
    window: 16ms

# espsense:
#   plugs:
#     - name: ${device_name}
#       power_sensor: garage_fridge_power
#       current_sensor: garage_fridge_current
#       voltage_sensor: garage_fridge_voltage

garage_fridge:
  heat_output: fridge_heater_output
  fridge_heat_sensor_name: Garage Fridge Heater
  fridge_control:
    sensor: fridge_temp
    min_temperature: 34
    kp: 0.49460
    ki: 0.00487
    kd: 12.56301
  freezer_control:
    sensor: freezer_temp
    max_temperature: 15
    cool_trigger_temperature: 40
    kp: 0.49460
    ki: 0.00487
    kd: 12.56301

modbus:

output:
  - platform: slow_pwm
    pin: D5
    id: fridge_heater_output
    period: 15s

sensor:
  - platform: inkbird_ibsth1_mini
    mac_address: "10:08:2C:1F:33:63"
    temperature:
      id: fridge_temp
      name: Garage Fridge Temperature
    humidity:
      name: Garage Fridge Humidity
    battery_level:
      name: Garage Fridge Sensor Battery Level
  - platform: inkbird_ibsth1_mini
    mac_address: "64:69:4E:9D:46:A9"
    temperature:
      id: freezer_temp
      name: Garage Freezer Temperature
    humidity:
      name: Garage Freezer Humidity
    battery_level:
      name: Garage Freezer Sensor Battery Level
  - platform: pzemac
    update_interval: 2s
    current:
      id: garage_fridge_current
      name: ${device_name} Current
    voltage:
      id: garage_fridge_voltage
      name: ${device_name} Voltage
    energy:
      name: ${device_name}
    power:
      id: garage_fridge_power
      name: ${device_name} Power
    frequency:
      name: ${device_name} Power Frequency
    power_factor:
      name: ${device_name} Power Factor

uart:
  rx_pin: D3
  tx_pin: D1
  baud_rate: 9600
