substitutions:
  device_id: master_bath_fan
  device_name: Master Bathroom Fan
  ip_address: !secret master_bath_fan_ip
  ota_pwd: !secret master_bath_fan_ota_pwd
  api_pwd: !secret master_bath_fan_api_pwd
  ap_wifi_pwd: !secret master_bath_fan_ap_wifi_pwd
  fan_wattage: "26.6"

packages:
  device_base: !include ../packages/feit_dimmer_as_fan.yaml
