substitutions:
  device_id: master-bath-hum-temp-sensor
  device_name: Master Bathroom Humidity and Temperature Sensor
  board: d1_mini
  ip_address: !secret master-bath-hum-temp-sensor-ip
  ota_pwd: !secret master-bath-hum-temp-sensor-ota-pwd
  api_pwd: !secret master-bath-hum-temp-sensor-api-pwd
  ap_wifi_pwd: !secret master-bath-hum-temp-sensor-ap-pwd

packages:
  device_base: !include ../packages/device_base.yaml

binary_sensor:
  - platform: template
    id: trigger_humidity
    lambda: return (id(humidity).state - id(median_humidity).state) > 5;
    filters:
      - delayed_off: 5min

i2c:
  sda: D2
  scl: D1
  scan: true
  
output:
  - platform: gpio
    pin: D3
    id: bme_gnd

sensor:
  - platform: bme280
    temperature:
      id: temperature
      name: "Master Bathroom Temperature"
    pressure:
      id: pressure
      name: "Master Bathroom Pressure"
    humidity:
      id: humidity
      name: "Master Bathroom Humidity"
    address: 0x76
    update_interval: 15s
  - platform: template
    name: "Master Bathroom Median Humidity"
    id: median_humidity
    unit_of_measurement: '%'
    icon: mdi:water-percent
    lambda: return id(humidity).state;
    update_interval: 60s
    filters:
      - median:
          window_size: 360
          send_every: 2
          send_first_at: 2

status_led:
  pin:
    number: D4
    inverted: true
