substitutions:
  device_id: master_bath_lights_2
  device_name: Master Bathroom Lights 2
  ip_address: !secret master_bath_lights_2_ip
  ota_pwd: !secret master_bath_lights_2_ota_pwd
  api_pwd: !secret master_bath_lights_2_api_pwd
  ap_wifi_pwd: !secret master_bath_lights_2_ap_wifi_pwd

packages:
  feit_dimmer: !include ../packages/feit_dimmer.yaml

light:
  - platform: tuya_light_plus
    id: tuya_light
    name: ${device_name}
    switch_datapoint: 1
    dimmer_datapoint: 2
    max_value: 1000
    linked_lights:
    day_night:
      sensor_id: sensor.day_night
      sensor_type: text
      sensor_day_value: Day
      sensor_night_value: Night
      day_default_brightness: 255
      night_default_brightness: 1
      day_auto_off_time: 0 min
      night_auto_off_time: 15 min
