substitutions:
  device_id: office_light
  device_name: Office Light
  ip_address: !secret office_light_ip
  ota_pwd: !secret office_light_ota_pwd
  api_pwd: !secret office_light_api_pwd
  ap_wifi_pwd: !secret office_light_ap_wifi_pwd
  day_brightness: "1"
  night_brightness: ".01"
  day_auto_off_minutes: "0"
  night_auto_off_minutes: "15"
  linked_lights: ""
  double_tap_while_off_stays_on: "true"

script:
  - id: startup
    then:
      - lambda: |-

packages:
  feit_dimmer: !include ../packages/feit_dimmer_new.yaml
