substitutions:
  device_id: pool_and_patio_lights
  device_name: Pool and Patio Lights
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret pool_and_patio_lights_ip
  ota_pwd: !secret pool_and_patio_lights_ota_pwd
  api_pwd: !secret pool_and_patio_lights_api_pwd
  ap_wifi_pwd: !secret pool_and_patio_lights_ap_wifi_pwd

packages:
  device_base: !include ../packages/device_base.yaml

esphome:
  includes:
    - ../custom/TreoLedPoolLight.h

external_components:
  - source:
      type: local
      path: ../components 
    components: [ binary_light_with_power, total_daily_energy ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

binary_sensor:
  - platform: gpio
    id: patio_lights_button
    pin:
      number: 12
      mode: INPUT_PULLUP
    on_press:
      then:
        - homeassistant.service:
            service: homeassistant.toggle
            data:
              entity_id: light.patio_lights
  - platform: gpio
    id: pool_lights_button
    pin:
      number: 5
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: pool_lights
  - platform: gpio
    id: color_button
    pin:
      number: 3
      mode: INPUT_PULLUP
    on_press:
      then:
        - lambda: |-
            Treo->next_color();
  - platform: homeassistant
    id: patio_lights
    entity_id: light.patio_lights
    on_press:
      then:
        - switch.turn_on: patio_lights_indicator
    on_release:
      then:
        - switch.turn_off: patio_lights_indicator

espsense:
  plugs:
    - name: Pool Lights
      power_sensor: pool_light_power
      voltage: 120

light:
  - platform: custom
    lambda: |-
      Treo = new TreoLedPoolLight(15);
      App.register_component(Treo);
      return {Treo};
    lights:
      - id: pool_lights
        name: "Pool Lights"
        on_turn_on:
          - sensor.template.publish:
              id: pool_light_power
              state: 10.0
        on_turn_off:
          - sensor.template.publish:
              id: pool_light_power
              state: 0.0

sensor:
  - platform: template
    name: Pool Lights Power
    id: pool_light_power
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    accuracy_decimals: 1
  - platform: total_daily_energy
    name: Pool Lights
    power_id: pool_light_power
    method: left
    min_save_interval: 10min

status_led:
  pin:
    number: 0
    inverted: true

switch:
  - platform: gpio
    id: patio_lights_indicator
    pin: 13

time:
  - platform: homeassistant
