#!/usr/bin/env python3
"""Generate a throwaway devices/secrets.yaml so CI can run `esphome config`.

The real devices/secrets.yaml is gitignored, but every device config references it
via `!secret`, so validation cannot run without one. This scans the tracked YAML for
`!secret <name>` references and writes a placeholder value for each.

The values are deliberately fake and are only ever used for config validation --
nothing generated here is flashed to a device or connected to a network. Refuses to
overwrite an existing secrets.yaml so it can never clobber real secrets locally.
"""

import base64
from pathlib import Path
import re
import subprocess
import sys

REPO_ROOT = Path(__file__).resolve().parent.parent
DEVICES_DIR = REPO_ROOT / "devices"
SECRETS_FILE = DEVICES_DIR / "secrets.yaml"

SECRET_RE = re.compile(r"!secret\s+([A-Za-z0-9_]+)")

# api `encryption.key` must be a valid base64-encoded 32-byte key.
PLACEHOLDER_API_KEY = base64.b64encode(b"esphome-ci-placeholder-key-32byt").decode()
# ota + wifi ap passwords must be non-empty; ap password needs >= 8 characters.
PLACEHOLDER_PASSWORD = "ci-placeholder-password"
PLACEHOLDER_SSID = "ci-placeholder-ssid"


def placeholder_for(name):
    if name.endswith("_key"):
        return PLACEHOLDER_API_KEY
    if name.endswith("_ssid"):
        return PLACEHOLDER_SSID
    return PLACEHOLDER_PASSWORD


def tracked_yaml():
    """Yield tracked YAML files under devices/ and components/.

    Uses git rather than a filesystem walk so local build output (devices/build/,
    **/.esphome/) is skipped -- those are gitignored, can hold thousands of files,
    and never contain !secret references we care about.
    """
    result = subprocess.run(
        ["git", "ls-files", "-z", "devices/*.yaml", "components/*.yaml"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    for entry in result.stdout.split("\0"):
        if entry:
            yield REPO_ROOT / entry


def referenced_secrets():
    names = set()
    for path in tracked_yaml():
        if path == SECRETS_FILE:
            continue
        names.update(SECRET_RE.findall(path.read_text(encoding="utf-8")))
    return sorted(names)


def main():
    if SECRETS_FILE.exists():
        print(
            f"generate_ci_secrets: {SECRETS_FILE.name} already exists, refusing to overwrite"
        )
        return 1

    names = referenced_secrets()
    if not names:
        print("generate_ci_secrets: no !secret references found")
        return 1

    lines = [
        "# Generated by scripts/generate_ci_secrets.py for CI config validation.",
        "# These are placeholders, not real secrets. Do not commit this file.",
        "",
    ]
    lines.extend(f"{name}: {placeholder_for(name)}" for name in names)
    SECRETS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(
        f"generate_ci_secrets: wrote {len(names)} placeholder secrets to {SECRETS_FILE}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
