substitutions:
  log_level: none
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ip_subnet: !secret ip_subnet
  ip_gateway: !secret ip_gateway

esphome:
  name: ${device_id}
  platform: ${platform}
  board: ${board}
  arduino_version: latest
  build_path: ../build/${device_id}

packages:
  wifi:             !include wifi/wifi.yaml
  api:              !include api/api.yaml
  ota:              !include ota/ota.yaml
  logger:           !include logger/logger.yaml
  status_sensor:    !include binary_sensor/status.yaml
  uptime_sensor:    !include sensor/uptime.yaml
  wifi_sensor:      !include sensor/wifi.yaml
  restart_switch:   !include switch/restart.yaml
  version_sensor:   !include text_sensor/version.yaml
  wifi_info_sensor: !include text_sensor/wifi_info.yaml

