substitutions:
  board: esp01_1m
  log_baud_rate: '0'

external_components:
  - source:
      type: local
      path: ../components 
    components: [ tuya_dimmer_as_fan ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

packages:
  base:   !include device_base_esp8266.yaml
  uart:   !include uart/tuya.yaml

espsense:
  plugs:
    - name: ${device_name}
      power_sensor: power
      voltage: 120

fan:
  - platform: tuya_dimmer_as_fan
    id: tuya_fan
    name: ${device_name}
    switch_datapoint: 1
    dimmer_datapoint: 2
    dimmer_max_value: 1000
    power:
      id: power
      name: ${device_name} Power
      fan_wattage: ${fan_wattage}

sensor:
  - platform: total_daily_energy
    name: ${device_name}
    power_id: power
    method: left

time:
  - platform: homeassistant

tuya:
