substitutions:
  platform: ESP8266
  board: esp01_1m

external_components:
  - source:
      type: local
      path: ../components 
    components: [ tuya_light_plus ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

espsense:
  plugs:
    - name: ${device_name}
      power_sensor: power
      voltage: 120

packages:
  base:   !include device_base.yaml
  logger: !include logger/logger_no_serial.yaml
  uart:   !include uart/tuya.yaml

sensor:
  - platform: total_daily_energy
    name: ${device_name}
    power_id: power
    method: left
    min_save_interval: 10min

time:
  - platform: homeassistant

tuya:
