substitutions:
  platform: ESP8266
  board: esp01_1m

external_components:
  - source:
      type: local
      path: ../components 
    components: [ tuya, tuya_dimmer_as_fan ]

packages:
  base:   !include device_base.yaml
  logger: !include logger/logger_no_serial.yaml
  uart:   !include uart/tuya.yaml

tuya:

fan:
  - platform: tuya_dimmer_as_fan
    id: tuya_fan
    name: ${device_name}
    switch_datapoint: 1
    dimmer_datapoint: 2
    dimmer_max_value: 1000
