substitutions:
  board: esp01_1m

external_components:
  - source:
      type: local
      path: ../components 
    components: [ tuya_light_plus ]

packages:
  base:   !include device_base_esp8266.yaml
  uart:   !include uart/tuya.yaml

tuya:
