substitutions:
  board: esp01_1m

external_components:
  - source:
      type: local
      path: ../components 
    components: [ tuya_light_plus ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

packages:
  base:   !include device_base_esp8266.yaml
  uart:   !include uart/tuya.yaml

espsense:
  plugs:
    - name: ${device_name}
      power_sensor: power
      voltage: 120

sensor:
  - platform: total_daily_energy
    name: ${device_name}
    icon: mdi:flash
    power_id: power
    method: left

time:
  - platform: homeassistant

tuya:
