substitutions:
  platform: ESP8266
  board: esp01_1m

external_components:
  - source:
      type: local
      path: ../components 
    components: [ tuya, tuya_dimmer_as_fan, total_daily_energy ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

packages:
  base:   !include device_base.yaml
  logger: !include logger/logger_no_serial.yaml
  uart:   !include uart/tuya.yaml

espsense:
  plugs:
    - name: ${device_name}
      power_sensor: power
      voltage: 120

fan:
  - platform: tuya_dimmer_as_fan
    id: tuya_fan
    name: ${device_name}
    switch_datapoint: 1
    dimmer_datapoint: 2
    dimmer_max_value: 1000
    power:
      id: power
      name: ${device_name} Power
      fan_wattage: ${fan_wattage}

sensor:
  - platform: total_daily_energy
    name: ${device_name}
    power_id: power
    method: left
    min_save_interval: 10min

time:
  - platform: homeassistant

tuya:
