substitutions:
  platform: ESP8266
  board: esp01_1m

external_components:
  - source:
      type: local
      path: ../components 
    components: [ tuya, tuya_light_plus ]
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

espsense:
  plugs:
    - name: ${device_name}
      power_sensor: power
      voltage: 120

packages:
  base:   !include device_base.yaml
  logger: !include logger/logger_no_serial.yaml
  uart:   !include uart/tuya.yaml

sensor:
  - platform: integration
    name: ${device_name}
    sensor: power
    integration_method: left
    time_unit: h
    unit_of_measurement: Wh
    device_class: energy
    state_class: measurement

time:
  - platform: homeassistant

tuya:
