CONF_PRIMARY_PUMP = "primary_pump"
CONF_AUXILIARY_PUMP = "auxiliary_pump"
CONF_AUXILIARY_PUMPS = "auxiliary_pumps"

CONF_SCHEDULES = "schedules"
CONF_RUNTIMES = "runtimes"
CONF_START_TIME = "start_time"
CONF_END_TIME = "end_time"
CONF_MINUTES_PER_HOUR = "minutes_per_hour"
CONF_SCHEDULE_SELECT = "schedule_select"
CONF_SEQUENCE_DELAY = "sequence_delay"
CONF_DISABLE_PUMPS_SENSOR = "disable_pumps_sensor"

CONF_CURRENT_SENSOR = "current_sensor"
CONF_ANOMALY_DETECTION_SWITCH = "anomaly_detection_switch"
CONF_ANOMALY_BASELINE_RESET_BUTTON = "anomaly_baseline_reset_button"
CONF_ANOMALY_STATUS_BINARY_SENSOR = "anomaly_status_binary_sensor"
CONF_ANOMALY_THRESHOLD_PCT = "anomaly_threshold_pct"
CONF_LEARNING_SAMPLES = "learning_samples"
CONF_ON_ANOMALY = "on_anomaly"

CONF_CURRENT_ON_THRESHOLD = "current_on_threshold"
CONF_NO_CURRENT_BINARY_SENSOR = "no_current_binary_sensor"

CONF_FLOW_SENSOR = "flow_sensor"
CONF_FLOW_TIMEOUT = "flow_timeout"
CONF_FLOW_LOSS_BINARY_SENSOR = "flow_loss_binary_sensor"
CONF_UNEXPECTED_FLOW_BINARY_SENSOR = "unexpected_flow_binary_sensor"
